site_name: Cloudrock Documentation
site_description: Documentation of an open-source marketplace platform Cloudrock. See the latest version at https://docs.cloudrock.ca
theme:
  name: material
  palette:
    primary: blue-grey
  analytics:
    gtag: 
  logo: assets/cloudrock-logo.png
  favicon: assets/cloudrock-logo.png
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - pdf-export:
      enabled_if_env: ENABLE_PDF_EXPORT
  - git-revision-date
  - render_swagger
  - print-site:
      print_page_title: 'Print documentation'
      enumerate_headings: true
      add_cover_page: true
      exclude:
        - API/
        - API/*
copyright: Copyright &copy; 2022 Cloudrock team
